### ISSUE TITLE
Crear Modelo de Entidades

### ISSUE THREAD

**Issue by zulma13** [Felipeceballos12/StartApp#11]
Responsable todo el equipo:
Rubén Cárdenas
Juan Felipe Contreras
Felipe Ceballos
Zulma Cárdenas

**Comment by Felipeceballos12** [comment]
Modelos de Entidades V1

![index](https://user-images.githubusercontent.com/25309408/134215425-e09ad6a7-358c-46f8-8510-7dc98ef83c5e.jpg)

**Comment by Felipeceballos12** [comment]
Modelo de Entidades V2

![image](https://user-images.githubusercontent.com/25309408/134215498-a2fe25eb-8695-49d5-ab63-f448d688c09c.png)

**Comment by Felipeceballos12** [comment]
Modelo de Entidades V3

![image](https://user-images.githubusercontent.com/25309408/134363598-60662c0c-5280-4106-8b58-f621bca3ec5d.png)

**Comment by Felipeceballos12** [comment]
Modelo de Entidades V3

![image](https://user-images.githubusercontent.com/25309408/134363860-15ed64cd-82a5-4fe6-8eb9-190c02cb2333.png)
