### ISSUE TITLE
Los horarios de reunión.

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartApp#3]
Deben considerar una reunión diaria de seguimiento, de 15 minutos, y por lo menos dos espacios adicionales entre semana para otro tipo de reuniones.

**Comment by Rudarkia** [comment]
Se define con el equipo una reunión diaria de seguimiento, de 15 minutos de 12:00 p.m. a 12:15 p.m. y para otro tipo de reuniones se estipulan de 10:00 a.m. a 11:00 a.m.
