### ISSUE TITLE
Los objetivos de los miembros del equipo.

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartApp#4]
Se refieren a objetivos relacionados con un equipo existoso. Tienen que ver con la calidad esperada, el cumplimiento de los planes, entre otros. Deben poder ser medibles y alcanzables en el tiempo del proyecto.

**Comment by Rudarkia** [comment]
Diseñar y desarrollar una aplicación web que permita el correcto funcionamiento del software,  ajustándolos a los requisitos solicitados por el cliente.
