### ISSUE TITLE
Coordinar reuniones y elaborar informe de  seguimiento.

### ISSUE THREAD

**Issue by Rudarkia** [Felipeceballos12/StartApp#48]
se entrega informe pendiente de la semana pasada 
[INFORME DE SEGUIMIENTO 1 semana del 13 al 19 de septiembre 2021.docx](https://github.com/Felipeceballos12/StartApp/files/7213117/INFORME.DE.SEGUIMIENTO.1.semana.del.13.al.19.de.septiembre.2021.docx)

**Comment by zulma13** [comment]
[INFORME DE SEGUIMIENTO  2 semana del  20 - 27 septiembre.docx](https://github.com/Felipeceballos12/StartApp/files/7213166/INFORME.DE.SEGUIMIENTO.2.semana.del.20.-.27.septiembre.docx)
