### ISSUE TITLE
Lider del equipo

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartApp#5]
Publicar el formato de conformación de equipo en el aula virtual. Si hay dudas, transmitirlas al profesor.

**Comment by zulma13** [comment]
Se reenvia acta numero 1,  esta actividad ya se había subido con anterioridad por parte del compañero Felipe Ceballos, el acta  contiene lo realizado en días anteriores, donde se conforma el equipo sus roles y se define el nombre del grupo y se crea el logo del mismo.

([[ACTA N° 1  Equipo #3 STARTAPP Grupo Desarrollo de Software 54.docx](https://github.com/Felipeceballos12/StartApp/files/7197798/ACTA.N.1.Equipo.3.STARTAPP.Grupo.Desarrollo.de.Software.54.docx)]([url](url)))
