### ISSUE TITLE
Diseñador de software

### ISSUE THREAD

**Issue by Felipeceballos12** [Felipeceballos12/StartApp#7]
Buscar por los menos tres características del lenguaje de programación C# y contarlas a los compañeros.

**Comment by contreras-juan** [comment]
C# es un lenguaje de programación orientada a objetos que tiene principalmente la siguientes características:

- Es Moderno: es un lenguaje de programación que es consistente con las recientes tendencias tecnológicas y requisitos de desarrollo.
- Es orientado a objetos.
- Es seguro: solo puede acceder a la memoria de las máquinas locales cuando se tienen los permisos para ello.
